#!/bin/bash

# Update the package repository and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'
# Create a basic HTML page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

service nginx start
