#!/bin/env bash
# Update the package repository and install Nginx
apt-get update

# Install nginx web server
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
