#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

#Update the package list
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend nana-aba-frontend
        bind *:80
        mode http
        default_backend nana-aba-backend
backend nana-aba-backend
        balance roundrobin
        server 398966-web-01 34.232.76.165 check
        server 398966-web-02 54.208.30.45 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
