#!/usr/bin/env bash
# Configure an Nginx server to listen on port 80

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sitesenabled/default
# restart nginx
service nginx restart
